### ISSUE TITLE
How to evaluate the model ?

### ISSUE THREAD

**Issue by kartikwar** [xmlyqing00/WaterNet#2]
I am trying to run the file eval_WaterNet.py but I am not sure what to specify in --video_name. Can you help ?

**Comment by xmlyqing00** [comment]
Sorry for the late reply. Now we have released the detailed documents. We recommend you to download our WaterDataset (see README.md). It's about 2GB. The video_name means the video in the WaterDataset. 

If you want to evaluate your own video, it is easy to prepare the `video` and the `first frame mask` following the WaterDataset file structure.

Feel free to ask me if you have further questions.
